# Generated by Django 2.2 on 2022-09-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
