# Generated by Django 2.2 on 2022-10-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_api', '0003_auto_20220908_1908'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='items',
            table='Items',
        ),
    ]
